### ISSUE TITLE
Fixed wireframe and view handling

### ISSUE THREAD

**Issue by yuta24** [rizumita/Selm#1]
`wireframe` と `view` のハンドリング方法を決めたい。

**Comment by rizumita** [comment]
@yuta24 アイデアあったら教えてください。

**Comment by rizumita** [comment]
@yuta24 
routeとviewを分ける必要が無いのではと思って、一本化しました。
https://github.com/rizumita/SelmSample/pull/1

**Comment by yuta24** [comment]
@rizumita 
改めてみてみましたが、大きな問題はないように思いました。問題だと考えている箇所がどこだか記載いただいてもよいですか？
View周りの更新方法を個別に記載しなきゃいけないのは面倒だとは思いますが（VirtualDOMみたいな差分更新の仕組みが欲しくなります）。

**Comment by rizumita** [comment]
@yuta24 
View controllerが読み込まれたときやBackボタンで戻ったときに、viewの実行やモデルの破棄を行うためにdispatchを実行する必要があるところですね。仕方ないのかなぁとは思ってるんですが。

**Comment by yuta24** [comment]
あー、それは悩ましいですね。 ReSwift も同じような実装なので、使いづらいなと思ったことを思い出しましたw

単なるアイディアですが、RIBsの [State Management](https://github.com/uber/RIBs/wiki#state-management)が参考にならないかなーと思いました。ちょっとRIBsの実装を追ってみます。

**Comment by rizumita** [comment]
@yuta24 
Life cycleに対応するメカニズムを書いてみました。

https://github.com/rizumita/SelmSample/blob/d66e1b1b5edfcb12b9874820309147a7cd6a7c35/SelmSample/Event/EventWireframe.swift#L9

自動化の部品もSampleに直書きしているので、ちょっと見にくいかと思いますが、各部品をLifecycleMsgProtocol / ViewProtocol / LifecycleWireframeProtocolに適合させて、view controllerを生成するときにobserveするメソッドを実行しておくと、Method Swizzlingで変更したviewDidLoadなどから発火して自動的にdispatchが実行されるようになっています。

これ以上実装の作業を少なくする方法は思いついてないです。

**Comment by yuta24** [comment]
> Method Swizzling

おー、黒魔法！ですが、 Pure Swiftでは実現が難しいので現実的な選択になりますね。個人的には良さそうな実装だと思います！

**Comment by rizumita** [comment]
@yuta24 ほかの方法も思いつかないので、Selmの方にいれてみます。

**Comment by yuta24** [comment]
なんの力にもなれなかったですが、とりあえず、このIssueはクローズしておきます！
問題ありそうであれば、リオープンしてくださいー。

**Comment by rizumita** [comment]
@yuta24 いやいや、相談のってもらって良かったです。ありがとうございます。
